# Generated by Django 3.2.18 on 2023-02-20 21:03

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230219_1944'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unigue_subscriber',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('author')), _negated=True), name='no_follow_myself'),
        ),
    ]
